AnBinhMarket-master/AnBinhMarket/Areas/Admin/Controllers/ManageReceiptController.cs
using AnBinhMarket.Data;
using AnBinhMarket.Data.Entities;
using AnBinhMarket.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AnBinhMarket.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ManageReceiptController : CustomController
    {
        private readonly ApplicationDbContext _context;

        public ManageReceiptController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index(string? textSearch)
        {
            var hoaDons = _context.HoaDons.Where(x=>!x.IsDeleted).Include(x => x.GioHang).ThenInclude(x => x.ChiTietGioHangs).Include(x=>x.GioHang).ThenInclude(x=>x.TaiKhoan).Select(h => h);
            if (textSearch != null)
            {
                hoaDons = hoaDons.Where(x=>x.Id.ToString().Contains(textSearch));
            }
            var result = new List<HoaDonViewModel>();
            foreach (var hoaDon in hoaDons)
            {
                decimal thanhTien = 0;

                foreach (var ctgh in hoaDon.GioHang.ChiTietGioHangs)
                {
                    thanhTien += ctgh.Gia * ctgh.SoLuong;
                }
                result.Add(new HoaDonViewModel()
                {
                    ChuY = hoaDon.ChuY,
                    DiaChi = hoaDon.DiaChi,
                    NgayCapNhat = hoaDon.NgayCapNhat,
                    NgayTao = hoaDon.NgayTao,
                    ThanhTien = thanhTien + hoaDon.PhiShip,
                    TrangThai = hoaDon.TrangThai,
                     Id = hoaDon.Id, 
                     HoTen = hoaDon.GioHang.TaiKhoan.HoTen
                });
            }
            result = result.OrderByDescending(x => x.NgayTao).ToList();
            return View(result);
        }

        public IActionResult Details(Guid id)
        {
            var hoaDon = _context.HoaDons
                .Include(x => x.GioHang).ThenInclude(x => x.ChiTietGioHangs).ThenInclude(x => x.SanPham)
                .Include(x => x.GioHang).ThenInclude(x => x.TaiKhoan).FirstOrDefault(x => x.Id == id);

            if (hoaDon == null)
            {
                return RedirectToAction("Index", "NotFound", new { Area = "Admin" });

            }
            return View(hoaDon);
        }
        public IActionResult Edit(Guid id)
        {

            var hoaDon = _context.HoaDons.Include(x => x.GioHang).ThenInclude(x => x.ChiTietGioHangs).ThenInclude(x => x.SanPham)
                .Include(x => x.GioHang).ThenInclude(x => x.TaiKhoan).FirstOrDefault(x => x.Id == id);
            if (hoaDon == null)
            {
                return RedirectToAction("Index", "NotFound", new { Area = "Admin" });

            }
            return View(hoaDon);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(HoaDon hoaDon)
        {
            try
            {
                var _hoaDon = _context.HoaDons.FirstOrDefault(x => x.Id == hoaDon.Id);
                if (_hoaDon != null)
                {
                    _hoaDon.TrangThai = hoaDon.TrangThai;
                    _context.HoaDons.Update(_hoaDon);
                    _context.SaveChanges();
                }
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ViewBag.Error = "Lỗi nhập dữ liệu!" + ex.Message;
                return View(hoaDon);
            }

        }

        public IActionResult Delete(Guid id)
        {
            var hoaDon = _context.HoaDons.Include(x=>x.GioHang).ThenInclude(x=>x.TaiKhoan).FirstOrDefault(x=>x.Id == id);

            if (hoaDon == null)
            {
                return RedirectToAction("Index", "NotFound", new { Area = "Admin" });
            }
            return View(hoaDon);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(Guid id)
        {
            var hoaDon = _context.HoaDons.FirstOrDefault(x=>x.Id ==id);
            if (hoaDon != null)
            {
                hoaDon.IsDeleted = true;
                _context.HoaDons.Update(hoaDon);
                _context.SaveChanges();
            }
            setAlert("Xoá đơn hàng thành công!", "success");
            return RedirectToAction("Index");
        }
    }
}

AnBinhMarket-master/AnBinhMarket/Areas/Admin/Views/ManageReceipt/Delete.cshtml
@using AnBinhMarket.Data.Entities
@model HoaDon

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
<div class="content container-fluid">
    <div class="row">
        <div class="col-xl-8 offset-xl-2">
            <!-- Page Header -->
            <div class="page-header">
                <div class="row">
                    <div class="col">
                        <h3 class="page-title">Bạn có chắc chắn muốn xóa hóa đơn không?</h3>
                    </div>
                </div>
            </div>
            <!-- /Page Header -->

            <div class="card">
                <div class="card-body">
                    <!-- Form -->
                     
                        <div class="form-group">
                            <label><strong>Tên khách hàng:</strong></label>
                            @Html.DisplayFor(model => model.GioHang.TaiKhoan.HoTen, new { htmlAttributes = new { @class = "form-control" } })

                        </div>
                        <div class="form-group">
                            <label><strong>Ngày đặt:</strong></label>
                            @Html.DisplayFor(model => model.NgayTao, new { htmlAttributes = new { @class = "form-control" } })

                        </div>
                        <div class="form-group">
                            <label><strong>Trạng thái:</strong></label>
                            @Html.DisplayFor(model => model.TrangThai, new { htmlAttributes = new { @class = "form-control" } })
                        </div>
                        <div class="form-group">
                            <label><strong>Phí ship:</strong> </label>
                            @Html.DisplayFor(model => model.PhiShip, new { htmlAttributes = new { @class = "form-control" } })
                        </div>

                        <div class="form-group">
                            <label><strong>Ghi chú:</strong> </label>
                            @Html.DisplayFor(model => model.ChuY, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                        </div>

                        <div class="form-group">
                            <label><strong>Địa chỉ nhận hàng:</strong> </label>
                             @Html.DisplayFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                        </div>
                        <div class="mt-4">
                            @using (Html.BeginForm())
                            {
                                @Html.AntiForgeryToken()

                                <button class="btn btn-primary" type="submit">
                                    Xóa
                                </button>
                                <a href="@Url.Action("Index","ManageReceipt")" class="btn btn-link">Huỷ</a>
                            }

                        </div>
                   
                    <!-- /Form -->
                </div>
            </div>
        </div>
    </div>
</div>

AnBinhMarket-master/AnBinhMarket/Areas/Admin/Views/ManageReceipt/Details.cshtml
@using AnBinhMarket.Data.Entities
@model HoaDon

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="content container-fluid">
    <div class="row">
        <div class="col-xl-8 offset-xl-2">
            <!-- Page Header -->
            <div class="page-header">
                <div class="row">
                    <div class="col">
                        <h3 class="page-title">Xem chi tiết đơn hàng</h3>
                    </div>
                </div>
            </div>
            <!-- /Page Header -->

            <div class="card">
                <div class="card-body">
                    <!-- Form -->
                    <form method="post">

                        <div class="form-group">
                            <label><strong>Tên khách hàng:</strong> </label>
                            @Html.DisplayFor(model => model.GioHang.TaiKhoan.HoTen, new { htmlAttributes = new { @class = "form-control" } })
                        </div>
                        <div class="form-group">
                            <label><strong>Ngày đặt:</strong> </label>
                            @Html.DisplayFor(model => model.NgayTao, new { htmlAttributes = new { @class = "form-control" } })
                        </div>
                        <div class="form-group">
                            <label><strong>Trạng thái:</strong> </label>
                            @Html.DisplayFor(model => model.TrangThai, new { htmlAttributes = new { @class = "form-control" } })
                        </div>
                        <div class="form-group">
                            <label><strong>Phí ship:</strong> </label>
                            @{
                                decimal giaNum = Model.PhiShip;
                                string giaStr = string.Format("{0:0,000}", giaNum) + " VND";
                            }
                            @Html.DisplayFor(model => model.PhiShip, new { htmlAttributes = new { @class = "form-control" }, value = "@giaStr" })
                        </div>
                        <div class="form-group">
                            <label><strong>Ghi chú:</strong> </label>
                            @Html.DisplayFor(model => model.ChuY, new { htmlAttributes = new { @class = "form-control" } })
                        </div>
                        <div class="form-group">
                            <label><strong>Địa chỉ nhận hàng:</strong> </label>
                            @Html.DisplayFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control" } })
                        </div>
                    </form>
                    <!-- /Form -->
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header card-header-primary">
                    <h4 class="card-title">Sản phẩm</h4>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-hover">
                            <thead class="text-primary">
                                <tr>
                                    <th>Hình ảnh</th>
                                    <th>Tên sản phẩm</th>
                                    <th>Giá</th>
                                    <th>Số lượng</th>
                                </tr>
                            
                            </thead>
                            <tbody>
                                @foreach (var item in Model.GioHang.ChiTietGioHangs)
                                {
                                    <tr>
                                        <td>
                                            @{
                                                string imagePath = "~/products/" + item.SanPham.HinhAnh;
                                            }
                                            <img src="@Url.Content(imagePath)" width="50" class="img-thumbnail" />
                                            <br />
                                        </td>
                                        <td>@Html.DisplayFor(modelItem => item.SanPham.TenSP)</td>
                                        <td>@Html.DisplayFor(modelItem => item.Gia) VND</td>
                                        <td>@Html.DisplayFor(modelItem => item.SoLuong)</td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                    @{
                        decimal thanhTien = Model.GioHang.ChiTietGioHangs.Select(c => c.SoLuong * c.Gia).Sum() + Model.PhiShip;
                        string tong = string.Format("{0:0,000}", thanhTien);
                    }
                    <hr />
                    <div class="row">
                        <div class="col-md-9">
                              <a href="@Url.Action("Edit","ManageReceipt",new {id = Model.Id})"
                                               class="btn btn-primary">
                                                Sửa
                              </a>
                            <a href="@Url.Action("Index","ManageReceipt")" class="btn btn-link">Quay lại</a>
                             
                        </div>
                        <div class="col-md-3" style="font-weight:bold;">
                            Thành tiền: @tong VND
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

AnBinhMarket-master/AnBinhMarket/Areas/Admin/Views/ManageReceipt/Edit.cshtml
@model HoaDon
@using AnBinhMarket.Data.Entities
@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
<div class="content container-fluid">
    <div class="row">
        <div class="col-xl-8 offset-xl-2">
            <!-- Page Header -->
            <div class="page-header">
                <div class="row">
                    <div class="col">
                        <h3 class="page-title">Chỉnh sửa hóa đơn</h3>
                    </div>
                </div>
            </div>
            <!-- /Page Header -->

            <div class="card">
                <div class="card-body">
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-horizontal">
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            @Html.HiddenFor(model => model.Id)
                            @Html.HiddenFor(model => model.MaGioHang)
                            @Html.HiddenFor(model => model.GioHang.TaiKhoan.HoTen)
                            @Html.HiddenFor(model => model.NgayTao)
                            @Html.HiddenFor(model => model.PhiShip)
                            @Html.HiddenFor(model => model.ChuY)
                            @Html.HiddenFor(model => model.DiaChi)


                            @{
                                var selectList = new SelectList(
                                new List<SelectListItem>
                {
                        new SelectListItem {Text = "Chờ xác nhận", Value = "Chờ xác nhận"},
                        new SelectListItem {Text = "Đã xác nhận", Value = "Đã xác nhận"},
                        new SelectListItem {Text = "Đang lấy hàng", Value = "Đang lấy hàng"},
                        new SelectListItem {Text = "Đang vận chuyển", Value = "Đang vận chuyển"},
                        new SelectListItem {Text = "Đã giao", Value = "Đã giao"},
                        new SelectListItem {Text = "Đã hủy", Value = "Đã hủy"},
                }, "Value", "Text");
                            }
                            <div class="form-group">
                                @Html.LabelFor(model => model.TrangThai, "Tình trạng", htmlAttributes: new { @class = "control-label col-md-4" })
                                <div class="col-md-10">
                                    @Html.DropDownListFor(model => model.TrangThai, selectList, htmlAttributes: new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.TrangThai, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <input type="submit" value="Lưu" class="btn btn-sm btn-primary normal-text" />
                                    @Html.ActionLink("Quay lại", "Index", null, new { @class = "btn btn-sm btn-primary normal-text" })
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>

            @if (ViewBag.Error != null)
            {
                <br />
                <div class="alert alert-danger" role="alert">@ViewBag.Error</div>
            }
        </div>
    </div>
</div>
<script href="~/bundles/jqueryval"></script>

AnBinhMarket-master/AnBinhMarket/Areas/Admin/Views/ManageReceipt/Index.cshtml
@using AnBinhMarket.Data.Entities
@using AnBinhMarket.Models
@model IEnumerable<HoaDonViewModel>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

@section styles{
    <!-- Datepicker CSS -->
    <link rel="stylesheet" href="/Asset/css/bootstrap-datetimepicker.min.css" />
    <!-- Datatables CSS -->
    <link rel="stylesheet" href="/Asset/plugins/datatables/datatables.min.css" />
    <link href="/Asset/css/material-dashboard.css" rel="stylesheet" />
}
<!-- Start alert -->
<div class="content container-fluid">
    <!-- Page Header -->
    <div class="page-header">
        <div class="row">
            <div class="col">
                <h3 class="page-title">Quản lý đơn hàng</h3>
            </div>
        </div>
    </div>
    <!-- /Page Header -->
    <!-- Start alert -->
    <div class="row">
        <div class="col-4"></div>
        <div class="col-4">
            <div style="display: none" id="deletee" class="alert alert-danger text-center" role="alert"></div>
        </div>
        <div class="col-4"></div>

    </div>
    <div class="row pb-2">
            <div class="col-md-4 col-12">
                <label>Nhập mã đơn hàng</label>
                <input id="txtMaDh" class="form-control" type="text" />

            </div>
           
            <div class="col-md-4 col-12">
                <br />

                <button class="btn btn-outline-primary" id="btn-filter" onclick="filterReceipt()">Áp dụng</button>
            </div>
        </div>
    <!-- End alert -->

    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-hover table-center mb-0 datatable">
                            <thead>
                                <tr>
                                    <th>Mã</th>
                                    <th>Tên khách hàng</th>
                                    <th>Ngày đặt</th>
                                    <th>Trạng thái</th>
                                    <th>Tổng tiền</th>
                                    <th class="text-right">Hành động</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                <tr>
                                    <td>@Html.DisplayFor(modelItem => item.Id)</td>
                                    <td>@Html.DisplayFor(modelItem => item.HoTen)</td>
                                    <td>@item.NgayTao.ToLocalTime()</td>
                                    <td>@Html.DisplayFor(modelItem => item.TrangThai)</td>
                                    <td>@Html.DisplayFor(modelItem => item.ThanhTien) VND</td>
                                    @if (!item.TrangThai.Equals("Đã hủy") && !item.TrangThai.Equals("Đã giao"))
                                    {
                                        <td class="text-right">
                                            <a href="@Url.Action("Details","ManageReceipt",new {id = item.Id})"
                                               class="btn btn-sm bg-primary-light mr-2">
                                                <i class="far fa-eye mr-1"></i>Chi tiết
                                            </a>
                                            <a href="@Url.Action("Edit", "ManageReceipt", new { id = item.Id})"
                                               class="btn btn-sm bg-primary-light mr-2">
                                                <i class="far fa-edit mr-1"></i> Sửa
                                            </a>
                                            <a href="@Url.Action("Delete", "ManageReceipt", new { id = item.Id })"
                                               class="btn btn-sm bg-danger-light mr-2">
                                                <i class="far fa-trash-alt mr-1"></i> Xoá
                                            </a>
                                        </td>
                                    }
                                    else
                                    {
                                        <td class="text-right">
                                            <a href="@Url.Action("Details","ManageReceipt",new {id = item.Id})"
                                               class="btn btn-sm bg-primary-light mr-2">
                                                <i class="far fa-eye mr-1"></i>Chi tiết
                                            </a>
                                            <a href="@Url.Action("Delete", "ManageReceipt", new { id = item.Id })"
                                               class="btn btn-sm bg-danger-light mr-2">
                                                <i class="far fa-trash-alt mr-1"></i> Xoá
                                            </a>
                                        </td>
                                    }

                                </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>

    function filterReceipt(){
      let url;
    const {pathname } = window.location;
    var txtMaDh = document.getElementById('txtMaDh').value


            url = `${pathname}?textSearch=${txtMaDh}`;


            window.location = url;
    }

</script>