AnBinhMarket-master/AnBinhMarket/Models/Components/_DC_LienHe.cs
using AnBinhMarket.Data;
using AnBinhMarket.Data.Entities;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace AnBinhMarket.Models.Components
{ 
    public class _DC_LienHeViewComponent : ViewComponent
    {
        private ApplicationDbContext _context;
        private UserManager<ApplicationUser> userManager;
        private SignInManager<ApplicationUser> signInManager;

        public _DC_LienHeViewComponent(UserManager<ApplicationUser> userManager, ApplicationDbContext context, SignInManager<ApplicationUser> signInManager)
        {
            this.userManager = userManager;
            _context = context;
            this.signInManager = signInManager;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View();
        }
    }
}

AnBinhMarket-master/AnBinhMarket/Controllers/ContactController.cs
using AnBinhMarket.Data;
using AnBinhMarket.Data.Entities;
using AnBinhMarket.Models;
using Microsoft.AspNetCore.Mvc;

namespace AnBinhMarket.Controllers
{
    public class ContactController : Controller
    {
        public readonly ApplicationDbContext _context;

        public ContactController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public JsonResult Send(string name, string phone, string email, string address, string content)
        {
            var feedback = new PhanHoi();
            feedback.Ten = name;
            feedback.SoDT = phone;
            feedback.Email = email;
            feedback.NgayTao = DateTime.Now;
            feedback.DiaChi = address;
            feedback.NoiDung = content;

            var id = new ContactDao(_context).InsertFeedBack(feedback);
            if (id !=Guid.Empty)
                return Json(new
                {
                    status = true
                });
            else
                return Json(new
                {
                    status = false
                });
        }
    }
}

AnBinhMarket-master/AnBinhMarket/Views/Contact/Index.cshtml
@section styles{
    <link href="~/css/custom/contact2.css" rel="stylesheet" />
}
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section scripts{
    <script src="~/js/custom/contact.js"></script>
}

<section class="section">
    <div class="container bg-white my-2 py-3">
        <div class="row">
            <div class="col-lg-6 contact">
                <div class="row">
                    <h5 class="title-contactus">GỬI PHẢN HỒI CHO CHÚNG TÔI</h5>
                    <form class="user-form">
                        @await Component.InvokeAsync("_DC_LienHe")
                    </form>
                    <div class="form-button">
                        <button id="btnSend">Gửi phản hồi</button>
                    </div>
                </div>

            </div>
           
        </div>
    </div>
</section>

<script>
     document.getElementById("btnSend").addEventListener('click', () => {
        if (document.getElementById("txtAddress").value == '') {
            alert('Vui lòng nhập địa chỉ của bạn')
        }
        else if (document.getElementById("txtContent").value == '') {
            alert('Vui lòng nhập Nội dung')
        }
    })
</script>